#!/usr/bin/env bash
# Quick Start Guide for Playwright + Cucumber + Allure Framework

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Playwright + Cucumber + JavaScript + Allure Framework      ║"
echo "║  Quick Start Guide                                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Available Commands:"
echo ""
echo "1️⃣  RUN ALL TESTS:"
echo "   npm test"
echo "   - Runs all features with JSON output for Allure"
echo ""

echo "2️⃣  RUN UI TESTS:"
echo "   npm run test:ui"
echo "   - Runs all tests in tests/features/UIFeature/"
echo ""

echo "3️⃣  RUN API TESTS:"
echo "   npm run test:api"
echo "   - Runs all tests in tests/features/APIFeature/"
echo ""

echo "4️⃣  RUN PERFORMANCE TESTS:"
echo "   npm run test:performance"
echo "   - Runs lighthouse and load tests"
echo ""

echo "5️⃣  RUN SPECIFIC FEATURE:"
echo "   npm run test:login       # Test login scenarios"
echo "   npm run test:inventory   # Test inventory features"
echo ""

echo "6️⃣  VIEW ALLURE REPORT:"
echo "   npm run report:open"
echo "   - Opens allure-report/index.html in default browser"
echo ""

echo "7️⃣  DEBUG MODE:"
echo "   npm run debug"
echo "   - Runs login feature in dry-run mode (no execution)"
echo ""

echo "8️⃣  CODE QUALITY:"
echo "   npm run lint             # Run ESLint"
echo "   npm run format           # Format code with Prettier"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📊 TEST FRAMEWORK ARCHITECTURE:"
echo ""
echo "   Feature Files (Gherkin)"
echo "   ├─ tests/features/UIFeature/ (13 features)"
echo "   ├─ tests/features/APIFeature/ (1 feature)"
echo "   └─ tests/features/performance/ (2 features)"
echo ""
echo "   Step Definitions (JavaScript)"
echo "   ├─ tests/steps/ui/ (12 step files)"
echo "   ├─ tests/steps/api/ (4 step files)"
echo "   └─ tests/steps/performance/ (2 step files)"
echo ""
echo "   Page Objects"
echo "   └─ Pages/ (7 page object models)"
echo ""
echo "   Hooks & Configuration"
echo "   ├─ Setup/hooks.js (Browser lifecycle)"
echo "   ├─ cucumber.js (Cucumber config)"
echo "   └─ playwright.config.js (Playwright config)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "✅ WHAT'S CONFIGURED:"
echo "   ✓ Playwright (v1.58.2) - Browser Automation"
echo "   ✓ Cucumber (v9.5.0) - BDD Framework"
echo "   ✓ JavaScript - Test Implementation"
echo "   ✓ Allure - Advanced Reporting"
echo "   ✓ Headless Mode - Fast Execution"
echo "   ✓ 15 Feature Files - Comprehensive Test Coverage"
echo "   ✓ 18 Step Definition Files - Full Implementation"
echo "   ✓ Environment Configuration - Easy Customization"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🔍 GENERATE REPORTS:"
echo ""
echo "Option 1 - Pre-generated HTML Report (NO JAVA NEEDED):"
echo "   1. Run tests: npm test"
echo "   2. View report: npm run report:open"
echo "   3. Opens: allure-report/index.html"
echo ""
echo "Option 2 - Native Allure Report (REQUIRES JAVA):"
echo "   1. Install Java: https://www.oracle.com/java/technologies/javase-downloads.html"
echo "   2. Run: npx allure generate allure-results --clean -o allure-report"
echo "   3. View: npx allure open allure-report"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🏃 QUICK TEST EXAMPLES:"
echo ""
echo "Run single scenario:"
echo "   npx cucumber-js tests/features/UIFeature/login.feature"
echo ""
echo "Run with specific tags:"
echo "   npx cucumber-js --tags \"@smoke\""
echo "   npx cucumber-js --tags \"not @wip\""
echo ""
echo "Run with headless browser:"
echo "   HEADLESS=true npm test"
echo ""
echo "Show dry-run (no execution):"
echo "   npx cucumber-js --dry-run"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📁 OUTPUT DIRECTORIES:"
echo ""
echo "   allure-results/        - Allure test result artifacts"
echo "   allure-report/         - Generated HTML Allure report"
echo "   reports/               - HTML & JSON reports + screenshots"
echo "   test-results/          - JUnit XML and results JSON"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "⚙️  CONFIGURATION FILES:"
echo ""
echo "   cucumber.js            - Cucumber settings and formatters"
echo "   playwright.config.js   - Playwright browser settings"
echo "   Setup/hooks.js         - Cucumber hooks and browser setup"
echo "   package.json           - Dependencies and npm scripts"
echo "   .env                   - Environment variables"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🚦 TYPICAL TEST EXECUTION FLOW:"
echo ""
echo "   1. npm test              # Run tests → Generate JSON results"
echo "   2. Files created:"
echo "      - allure-results/*.json"
echo "      - reports/cucumber-report.html"
echo "   3. npm run report:open   # View Allure dashboard"
echo "   4. Analyze results"
echo "   5. Update tests as needed"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "💡 PRO TIPS:"
echo ""
echo "• Run tests in headless mode for CI/CD pipelines"
echo "• Use tags to organize and selectively run scenarios"
echo "• Take screenshots on failure (automatically configured)"
echo "• Check allure-report/index.html for test metrics"
echo "• Review failed tests in screenshots directory"
echo "• Update .env for different environments"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Framework Status: READY FOR PRODUCTION"
echo ""
echo "For full documentation, see: SETUP_COMPLETE.md"
echo ""
