// tests/specs/Broken.spec.js
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

// Array to store all broken link results from all tests
const allBrokenLinkResults = [];
const REPORT_DIR = path.resolve(__dirname, 'reports');
const MAX_RETRIES = 2; // Total attempts = MAX_RETRIES + 1 (original attempt)

// --- Report Generation Functions ---

// HTML Report Generator
function generateHtmlReport(data) {
  const timestamp = new Date().toLocaleString();
  const totalBrokenLinks = data.reduce((sum, item) => sum + item.brokenLinks.length, 0);
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Broken Link Report</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #d32f2f; margin-bottom: 10px; }
        .summary { background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0; }
        .summary p { margin: 5px 0; }
        h2 { color: #333; border-bottom: 2px solid #d32f2f; padding-bottom: 10px; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 30px; table-layout: fixed; }
        th, td { border: 1px solid #ddd; padding: 12px; vertical-align: top; text-align: left; }
        th { background: #f4f4f4; font-weight: bold; }
        td a { color: #d32f2f; text-decoration: none; word-break: break-all; }
        td a:hover { text-decoration: underline; }
        .url-cell { width: 40%; word-break: break-all; }
        .links-cell { width: 60%; word-break: break-all; }
        .broken-link { margin: 8px 0; padding: 8px; background: #ffebee; border-left: 3px solid #d32f2f; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 14px; }
        .no-issues { background: #d4edda; border-left: 4px solid #28a745; padding: 15px; margin: 20px 0; color: #155724; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>🔗 Broken Link Report</h1>
        <div class="summary">
          <p><strong>Report Generated:</strong> ${timestamp}</p>
          <p><strong>Total Categories Checked:</strong> ${Object.keys(data.reduce((acc, item) => ({ ...acc, [item.category]: true }), {})).length}</p>
          <p><strong>Total URLs Analyzed:</strong> ${data.length}</p>
          <p><strong>Total Broken Links Found:</strong> ${totalBrokenLinks}</p>
        </div>`;

  if (data.length === 0) {
    html += `<div class="no-issues"><strong>✅ Success!</strong> No broken links were found during the scan.</div>`;
  } else {
    const groupedReport = data.reduce((acc, item) => {
      if (!acc[item.category]) acc[item.category] = [];
      acc[item.category].push({ url: item.url, brokenLinks: item.brokenLinks });
      return acc;
    }, {});

    for (const category in groupedReport) {
      html += `<h2>📂 ${category}</h2>`;
      html += `<table>
        <thead>
          <tr>
            <th class="url-cell">Site URL</th>
            <th class="links-cell">Broken Links (${groupedReport[category].reduce((sum, site) => sum + site.brokenLinks.length, 0)})</th>
          </tr>
        </thead>
        <tbody>`;
      
      for (const site of groupedReport[category]) {
        const brokenLinksHtml = site.brokenLinks
          .map(link => `<div class="broken-link"><a href="${link}" target="_blank">${link}</a></div>`)
          .join('');
        html += `<tr>
          <td class="url-cell">${site.url}</td>
          <td class="links-cell">${brokenLinksHtml}</td>
        </tr>`;
      }
      html += `</tbody></table>`;
    }
  }

  html += `
        <div class="footer">
          <p>Generated by Playwright Broken Link Checker</p>
          <p>Max Retries: ${MAX_RETRIES} | Timeout: 15 seconds per link</p>
        </div>
      </div>
    </body>
    </html>`;
  
  return html;
}

// Markdown Report Generator
function generateMarkdownReport(data) {
  const timestamp = new Date().toLocaleString();
  const totalBrokenLinks = data.reduce((sum, item) => sum + item.brokenLinks.length, 0);
  
  let markdown = `# 🔗 Broken Link Report\n\n`;
  markdown += `**Report Generated:** ${timestamp}\n\n`;
  markdown += `## 📊 Summary\n\n`;
  markdown += `- **Total Categories Checked:** ${Object.keys(data.reduce((acc, item) => ({ ...acc, [item.category]: true }), {})).length}\n`;
  markdown += `- **Total URLs Analyzed:** ${data.length}\n`;
  markdown += `- **Total Broken Links Found:** ${totalBrokenLinks}\n\n`;
  markdown += `---\n\n`;

  if (data.length === 0) {
    markdown += `## ✅ Results\n\nNo broken links were found during the scan. All links are working correctly!\n\n`;
  } else {
    const groupedReport = data.reduce((acc, item) => {
      if (!acc[item.category]) acc[item.category] = [];
      acc[item.category].push({ url: item.url, brokenLinks: item.brokenLinks });
      return acc;
    }, {});

    for (const category in groupedReport) {
      const categoryBrokenCount = groupedReport[category].reduce((sum, site) => sum + site.brokenLinks.length, 0);
      markdown += `## 📂 ${category}\n\n`;
      markdown += `**Broken Links in Category:** ${categoryBrokenCount}\n\n`;
      markdown += `| Site URL | Broken Links |\n`;
      markdown += `|----------|-------------|\n`;

      for (const site of groupedReport[category]) {
        const linksMarkdown = site.brokenLinks.map(link => `• \`${link}\``).join('<br>');
        markdown += `| ${site.url} | ${linksMarkdown} |\n`;
      }
      markdown += `\n`;
    }
  }

  markdown += `---\n\n`;
  markdown += `*Generated by Playwright Broken Link Checker*\n`;
  markdown += `*Max Retries: ${MAX_RETRIES} | Timeout: 15 seconds per link*\n`;

  return markdown;
}

// JSON Report Generator
function generateJsonReport(data) {
  return JSON.stringify({
    generatedAt: new Date().toISOString(),
    summary: {
      totalCategories: Object.keys(data.reduce((acc, item) => ({ ...acc, [item.category]: true }), {})).length,
      totalUrls: data.length,
      totalBrokenLinks: data.reduce((sum, item) => sum + item.brokenLinks.length, 0)
    },
    results: data,
    configuration: {
      maxRetries: MAX_RETRIES,
      timeout: 15000,
      maxRedirects: 5
    }
  }, null, 2);
}

// --- Playwright Test Definition ---

test.afterAll(async () => {
  console.log('\n--- 📝 Generating Broken Link Reports ---');
  
  try {
    // 1. Ensure the reports directory exists
    if (!fs.existsSync(REPORT_DIR)) {
      fs.mkdirSync(REPORT_DIR, { recursive: true });
      console.log(`✅ Created report directory: ${REPORT_DIR}`);
    }

    // 2. Generate and write the HTML report
    const htmlReport = generateHtmlReport(allBrokenLinkResults);
    const htmlFilePath = path.join(REPORT_DIR, 'broken-links-report.html');
    fs.writeFileSync(htmlFilePath, htmlReport, 'utf8');
    console.log(`✅ HTML Report saved to: ${htmlFilePath}`);

    // 3. Generate and write the Markdown report
    const markdownReport = generateMarkdownReport(allBrokenLinkResults);
    const markdownFilePath = path.join(REPORT_DIR, 'broken-links-report.md');
    fs.writeFileSync(markdownFilePath, markdownReport, 'utf8');
    console.log(`✅ Markdown Report saved to: ${markdownFilePath}`);

    // 4. Generate and write the JSON report
    const jsonReport = generateJsonReport(allBrokenLinkResults);
    const jsonFilePath = path.join(REPORT_DIR, 'broken-links-report.json');
    fs.writeFileSync(jsonFilePath, jsonReport, 'utf8');
    console.log(`✅ JSON Report saved to: ${jsonFilePath}`);

    // 5. Summary
    if (allBrokenLinkResults.length === 0) {
      console.log('\n🎉 All links checked successfully. No broken links found!');
    } else {
      const totalBroken = allBrokenLinkResults.reduce((sum, item) => sum + item.brokenLinks.length, 0);
      console.log(`\n⚠️ Found ${totalBroken} broken links across ${allBrokenLinkResults.length} URLs.`);
      console.log(`📊 Check the reports in: ${REPORT_DIR}`);
      
      // Optional: Fail the test suite if broken links were found
      // throw new Error(`Test suite failed: ${totalBroken} broken links found`);
    }
  } catch (error) {
    console.error(' Error generating reports:', error.message);
    throw error;
  }
});

test.describe('Broken Links Validation', () => {
  const urlsToCheck = [
    { category: 'RideNow v7', url: 'https://ridenow.qa.dsp.leadventure.dev/new-used-inventory-for-sale--inventory' },
    { category: 'RideNow-AllInventory', url: 'https://ridenow.qa.dsp.leadventure.dev/new-used-inventory-for-sale--inventory' },
    { category: 'RideNow-Preowned', url: 'https://ridenow.qa.dsp.leadventure.dev/used-inventory-for-sale--inventory?condition=pre-owned&pg=1&sortby=Inventory|asc' },
    { category: 'RideNow-under10k', url: 'https://ridenow.qa.dsp.leadventure.dev/new-used-inventory-for-sale--inventory?pg=1&price=1-9999' },
    { category: 'Ridenow orlando', url: 'https://multi-site-inventory-2-v7.qa.dsp.leadventure.dev/--inventory' },
    { category: 'Marine-boat', url: 'https://marine-v6-complex.qa.dsp.leadventure.dev/new-boats-near-sebago-lake-maine--xNewInventory#page=xNewInventory&vt=boat' },
    { category: 'Marine-newOffRoad', url: 'https://marine-v6-complex.qa.dsp.leadventure.dev/new-boats-near-sebago-lake-maine--xallinventory?at=atv|sport%20sxs|utility%20vehicle' },
    { category: 'Marine-PreOwned', url: 'https://marine-v6-complex.qa.dsp.leadventure.dev/default.asp?page=xPreOwnedInventory' },
    {category:'RidenowFloridaviewInventory', url:'https://ridenowflorida.qa.dsp.leadventure.dev/default.asp?page=xNewInventory' },
    {category:'RidenowFloridaPreowned',url:'https://ridenowflorida.qa.dsp.leadventure.dev/default.asp?page=xPreOwnedInventory'},
    {category:'RidenowLasVegasInventory',url:'https://ridenowvegas.qa.dsp.leadventure.dev/default.asp?page=xPreOwnedInventory'},
  ];

  for (const { category, url } of urlsToCheck) {
    test(`Check broken links for ${category} - ${url}`, async ({ page, request }) => {
      console.log(`\n🔍 Starting check for: ${category}`);
      console.log(`   URL: ${url}`);

      try {
        await page.goto(url, { 
          waitUntil: 'domcontentloaded',
          timeout: 30000 
        });
      } catch (error) {
        console.error(` Failed to load page: ${url}`);
        console.error(`   Error: ${error.message}`);
        throw error;
      }

      // Extract all links from the page
      const links = await page.$$eval('a', anchors =>
        anchors
          .map(a => a.href)
          .filter(href => 
            href && 
            !href.startsWith('#') && 
            !href.startsWith('javascript:') &&
            !href.startsWith('mailto:') &&
            !href.startsWith('tel:') &&
            (href.startsWith('http://') || href.startsWith('https://'))
          )
      );
      
      const uniqueLinks = [...new Set(links)];
      console.log(`   Found ${uniqueLinks.length} unique links to check`);

      const brokenLinks = [];
      let checkedCount = 0;

      // Loop through each unique link found on the page
      for (const link of uniqueLinks) {
        checkedCount++;
        let isBrokenLink = false;
        let lastError = null;

        // Progress indicator
        if (checkedCount % 10 === 0) {
          console.log(`   Progress: ${checkedCount}/${uniqueLinks.length} links checked...`);
        }

        // --- RETRY LOOP START ---
        for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
          try {
            const response = await request.get(link, { 
              timeout: 15000, 
              maxRedirects: 5,
              ignoreHTTPSErrors: false
            });
            
            // Check for definitive 4xx or 5xx status code
            if (response.status() >= 400) {
              console.log(`    BROKEN: HTTP ${response.status()} - ${link}`);
              isBrokenLink = true;
              break; // Exit retry loop - definitive failure
            } else {
              // Success (status < 400)
              isBrokenLink = false;
              break; // Exit retry loop - success
            }

          } catch (error) {
            lastError = error;
            const errorMessage = error.message.toLowerCase();
            
            // Define common transient network/timeout errors
            const isTransientError = 
              errorMessage.includes('timeout') || 
              errorMessage.includes('connection') || 
              errorMessage.includes('net::') ||
              errorMessage.includes('econnrefused') ||
              errorMessage.includes('enotfound') ||
              errorMessage.includes('name not resolved'); 

            if (isTransientError) {
              if (attempt < MAX_RETRIES) {
                // If it's a transient error and we have retries left, retry
                console.log(`    Transient error for ${link.substring(0, 50)}... (Attempt ${attempt + 1}/${MAX_RETRIES + 1})`);
                await page.waitForTimeout(1000 * (attempt + 1)); // Exponential backoff
                continue; // Go to the next retry attempt
              } else {
                // Last attempt failed with a transient error - do NOT report as broken
                console.log(`    Skipping ${link.substring(0, 50)}... (transient error after ${MAX_RETRIES + 1} attempts)`);
                isBrokenLink = false;
                break; // Exit the retry loop
              }
            } else {
              // Non-transient error - report as broken immediately
              console.log(`    ERROR: ${link.substring(0, 50)}... - ${error.message.split('\n')[0]}`);
              isBrokenLink = true;
              break; // Exit the retry loop
            }
          }
        }
        // --- RETRY LOOP END ---

        // Record the link if it was determined to be broken
        if (isBrokenLink) {
          brokenLinks.push(link);
        }
      }

      // Store results if broken links were found
      if (brokenLinks.length > 0) {
        allBrokenLinkResults.push({
          category: category,
          url: url,
          brokenLinks: brokenLinks,
          totalLinksChecked: uniqueLinks.length,
          checkedAt: new Date().toISOString()
        });
        console.log(`\n ${category}: Found ${brokenLinks.length} broken links out of ${uniqueLinks.length} total links`);
      } else {
        console.log(`\n ${category}: All ${uniqueLinks.length} links are working correctly`);
      }
    });
  }
});